CREATE TABLE customers (
id INT PRIMARY KEY auto_increment,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50)
);


CREATE TABLE ORDERS (
ID INT PRIMARY KEY AUTO_INCREMENT,
ORDER_DATE DATE,
AMOUNT DECIMAL(8,2),
CUSTOMER_ID INT, 
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

DROP TABLE ORDERS;