CREATE TABLE employees (
ID INT PRIMARY KEY auto_increment,
LAST_NAME VARCHAR(100) NOT NULL,
FIRST_NAME VARCHAR(100) NOT NULL,
MIDDLE_NAME VARCHAR(100),
AGE INT NOT NULL,
CURRENT_STATUS VARCHAR(200) NOT NULL default 'EMPLOYED'
);
INSERT INTO employees(first_name, last_name, age) VALUES
('Dora', 'Smith', 58);

SELECT * FROM EMPLOYEES;
DESC EMPLOYEES;